# Generated by Django 3.2.11 on 2022-04-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('poster', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('datetime', models.CharField(max_length=30)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('price_preorder', models.FloatField(blank=True, null=True)),
                ('ticket_link', models.CharField(max_length=200)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.CharField(max_length=200)),
            ],
        ),
    ]
