# Generated by Django 3.2.11 on 2022-04-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_userchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchat',
            old_name='chat_id',
            new_name='id_chat',
        ),
        migrations.AlterField(
            model_name='eventnotified',
            name='ids_events',
            field=models.TextField(default='[]'),
        ),
    ]
