# Generated by Django 3.2.11 on 2022-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('str_value', models.TextField(null=True)),
                ('int_value', models.IntegerField(null=True)),
                ('bool_value', models.BooleanField(null=True)),
                ('float_value', models.FloatField(null=True)),
            ],
        ),
    ]
