# Generated by Django 3.2.11 on 2022-04-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_tagnotice_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue_address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_address_ext',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue_name_ext',
        ),
    ]
