# Generated by Django 3.2.11 on 2022-04-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_userchat_is_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagNotice',
            new_name='TagSubscription',
        ),
    ]
